apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deploy
  namespace: myspace
  labels:
    name: app-deploy

spec:
  replicas: 2
  selector:
    matchLabels:
      name: myapp-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp-pod

    spec:
      containers:
        - name: myapp-container
          image: stackupiss/northwind-app:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mydb-svc.myspace.svc.cluster.local
            - name: INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            requests:
              cpu: "100m"

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: myspace
  labels:
    name: myapp-svc
spec:
  type: LoadBalancer
  selector:
    name: myapp-pod
  ports:
    - port: 80
      targetPort: 3000
