apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: myapp-hpa
  namespace: myspace
  labels:
    name: myapp-hpa

spec:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 20
  scaleTargetRef:
    apiVersion: apps/v1
    name: app-deploy
    kind: Deployment